{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "javv.secretName" . }}
  labels:
    {{- include "javv.labels" . | nindent 4 }}
type: Opaque
stringData:
  token-pepper: {{ .Values.secrets.tokenPepper | quote }}
  bootstrap-admin-password: {{ .Values.secrets.bootstrapAdminPassword | quote }}
{{- end }}
