{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "javv.secretName" . }}
  labels:
    {{- include "javv.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret-key: {{ .Values.secrets.secretKey | quote }}
  bootstrap-admin-password: {{ .Values.secrets.bootstrapAdminPassword | quote }}
{{- end }}
