"""The ingest envelope model — the extra="forbid" wire contract with the scanner (v4, with v3
still accepted during the M8d ptype rollout — the one deliberate dual-acceptance window).
The golden fixture is generated by the REAL scanner package, so drift on either side fails here."""

import json
from pathlib import Path

import pytest
from pydantic import ValidationError

from backend.models.envelope import (
    SEVERITY_RANK,
    IngestEnvelope,
    TrivyTuning,
    canonical_severity,
)

GOLDEN = json.loads((Path(__file__).parent / "fixtures/envelope-trivy-golden.json").read_text())


def test_golden_envelope_from_the_real_scanner_validates() -> None:
    env = IngestEnvelope.model_validate(GOLDEN)
    assert env.scanner == "trivy" and env.schema_version == 4
    assert env.namespaces == ["javv-smoke", "team-b"] and env.replicas == 3
    assert len(env.findings) == 29 and env.counts.total == 29
    assert env.scanner_version == "0.71.2"  # provenance survives (D41)
    assert {f.ptype for f in env.findings} == {"os"}  # v4: the alpine scan is all os-pkgs


def test_v3_envelope_still_ingests_ptype_defaults_to_null() -> None:
    """The M8d no-flag-day window (B-1, #241): an un-swapped scanner's v3 envelope stays green;
    its findings simply carry no package type yet (the next v4 sweep heals them, D30)."""
    v3 = json.loads((Path(__file__).parent / "fixtures/envelope-trivy-v3-golden.json").read_text())
    env = IngestEnvelope.model_validate(v3)
    assert env.schema_version == 3
    assert all(f.ptype is None for f in env.findings)


def test_garbage_ptype_is_rejected_at_the_edge() -> None:
    # untrusted input landing in a keyword facet field — shape-constrained (lowercase vocab)
    for bad in ("OS", "os pkgs", "-leading", "a" * 65, ""):
        # mutate in place — a shortened findings list would trip the counts invariant instead
        findings = [{**GOLDEN["findings"][0], "ptype": bad}, *GOLDEN["findings"][1:]]
        with pytest.raises(ValidationError, match="ptype"):
            IngestEnvelope.model_validate({**GOLDEN, "findings": findings})


def test_extra_fields_are_rejected_everywhere() -> None:
    for mutation in (
        {**GOLDEN, "surprise": 1},  # top level
        {**GOLDEN, "counts": {**GOLDEN["counts"], "bonus": 1}},  # nested counts
        {**GOLDEN, "findings": [{**GOLDEN["findings"][0], "x": 1}]},  # per finding
    ):
        with pytest.raises(ValidationError):
            IngestEnvelope.model_validate(mutation)


def test_schema_versions_outside_the_dual_window_are_rejected() -> None:
    # the M8d window is exactly {3, 4} (D25/D35 + the B-1 no-flag-day exception) — anything
    # older is a pre-D44 scanner (422, swap the image), anything newer is a config error
    for version in (1, 2, 5):
        with pytest.raises(ValidationError):
            IngestEnvelope.model_validate({**GOLDEN, "schema_version": version})


def test_cluster_id_shape_is_enforced() -> None:
    # cluster_id flows into INDEX NAMES — strict shape kills index-name injection
    for bad in ("UPPER-case", "has space", "a", "x" * 65, "dots.not.ok", "slash/attack", ""):
        with pytest.raises(ValidationError):
            IngestEnvelope.model_validate({**GOLDEN, "cluster_id": bad})


def test_counts_invariant_is_enforced() -> None:
    # total must equal the bucket sum — cheap integrity check on untrusted input
    bad = {**GOLDEN, "counts": {**GOLDEN["counts"], "total": GOLDEN["counts"]["total"] + 1}}
    with pytest.raises(ValidationError):
        IngestEnvelope.model_validate(bad)


def test_server_rederives_severity_never_trusts_the_client_bucket() -> None:
    tampered = {**GOLDEN, "findings": [{**GOLDEN["findings"][0]}]}
    tampered["findings"][0]["severity"] = "LOW"
    tampered["findings"][0]["severity_canonical"] = "crit"  # lying client
    tampered["counts"] = {  # keep the envelope self-consistent so only the lie is under test
        **{k: 0 for k in ("crit", "high", "med", "low", "negligible", "unknown", "fixable")},
        "low": 1,
        "total": 1,
        "fixable": int(tampered["findings"][0]["fixable"]),
    }
    env = IngestEnvelope.model_validate(tampered)
    f = env.findings[0]
    assert f.severity_server == "low" and f.severity_rank == SEVERITY_RANK["low"]


def test_canonical_severity_maps_both_scanners_and_defends_garbage() -> None:
    assert canonical_severity("CRITICAL") == canonical_severity("Critical") == "critical"
    assert canonical_severity("Negligible") == "negligible"
    assert canonical_severity("weird") == canonical_severity("") == "unknown"
    assert SEVERITY_RANK == {
        "critical": 5,
        "high": 4,
        "medium": 3,
        "low": 2,
        "negligible": 1,
        "unknown": 0,
    }


# --- effective_config (D44/FR-25, schema v3) ----------------------------------


def test_golden_envelope_carries_effective_config() -> None:
    env = IngestEnvelope.model_validate(GOLDEN)
    assert env.effective_config.scope.ignore_namespaces == ["kube-system"]
    tuning = env.effective_config.tuning
    assert isinstance(tuning, TrivyTuning) and tuning.scanners == "vuln"  # trivy shape


def test_tuning_shape_must_match_the_scanner() -> None:
    # a trivy envelope carrying grype tuning (or vice versa) is a lying client — 422
    grype_tuning = {"only_fixed": False, "scope": None, "scan_timeout": 600}
    mutated = {**GOLDEN, "effective_config": {**GOLDEN["effective_config"], "tuning": grype_tuning}}
    with pytest.raises(ValidationError):
        IngestEnvelope.model_validate(mutated)


def test_effective_config_forbids_extras_and_is_required() -> None:
    for mutation in (
        {**GOLDEN, "effective_config": {**GOLDEN["effective_config"], "surprise": 1}},
        {**GOLDEN, "effective_config": None},
        {k: v for k, v in GOLDEN.items() if k != "effective_config"},
    ):
        with pytest.raises(ValidationError):
            IngestEnvelope.model_validate(mutation)


def test_scan_event_doc_carries_the_effective_config() -> None:
    from backend.services.ingest import build_docs

    docs = build_docs(IngestEnvelope.model_validate(GOLDEN))
    stamped = docs["scan_event"]["effective_config"]
    assert stamped["scope"]["ignore_namespaces"] == ["kube-system"]
    assert stamped["tuning"]["scanners"] == "vuln"
    # run-level metadata stays off the per-finding and image docs (D44)
    assert "effective_config" not in docs["findings"][0]
    assert "effective_config" not in docs["image"]
