{{- with .Values.opensearch.javv.auth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "javv-opensearch.adminSecret" (dict "javv" $.Values.opensearch.javv "Release" $.Release) }}
  labels:
    {{- include "javv-opensearch.labels" $ | nindent 4 }}
type: Opaque
stringData:
  password: {{ . | quote }}
{{- end }}
