_meta:
  type: "rolesmapping"
  config_version: 2
all_access:
  reserved: false
  backend_roles: ["admin"]
  description: "admin, the store's superuser"
javv:
  reserved: false
  users: ["javv"]
  description: "the backend's user"
